config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end


    get '/publicar', to: "welcome#publicar"

    get '/perfil', to: "welcome#perfil"
    

    put "/articles/:id/publicar", to: "articles#publicar"
   
    #adiciones que cuando se realize login con omniauth el controlador que se ejecuta 
    #es  omniauth_callbacks
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

    
    
    root 'welcome#index' 

    
    


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/parciales/_navegacion.html.erb
<header class="row" id="header-nav">
  <nav class= "col-xs-12 col-sm-12 col-md-12">
    <div class="nav-wrapper blue darken-2">
      <div class="container">

      <%= link_to(root_path, html_options = {class:"brand-logo"}) do %>
        <%= cl_image_tag("logof_yihg8h.png", id:"logo") %>
      <%end%>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down">
        <li><%=link_to "Inicio", root_path, class:"bold"%></li>
        <li><%=link_to "Articulos", articles_path, class:"bold" %></li>
        <% @categories.each do|category| %>
          <li><%= link_to category.name, category , class:"bold"%></li>
        <%end%>
        <% if user_signed_in? %>
          <li><a class='dropdown-button' href='#' data-activates='dropdown-perfil'>
          <% unless current_user.avatar.nil?%>
            <%= image_tag current_user.avatar , :class => "circle img-nav-perfil"%>
          <%else%>
            <i class="material-icons dp48 ">perm_identity</i>
          <%end%>
          </a></li>

          <ul id='dropdown-perfil' class='dropdown-content active-nav-perfil'>
            <% unless current_user.permission_level == 1%>
              <li><%=link_to "perfil" , perfil_path , class: "azul bold"%></li>  
            <%end%>
            <li class="divider"></li>
            <li><%=link_to "Salir", destroy_user_session_path, method: :delete, class: "azul bold" %></li>
          </ul>
        <%else%>
          <li><%= link_to "Iniciar sesion", new_user_session_path, class:"bold" %></li>
          <li><%= link_to "Crear cuenta", new_user_registration_path, class:"bold" %></li>
        <%end%>
      </ul>

      <ul class="side-nav " id="mobile-demo">
        <li><%=link_to "Inicio", root_path, class: "bold azul"%></li>
        <li><%=link_to "Articulos", articles_path , class: "azul bold"%></li>
        <% @categories.each do|category| %>
          <li><%= link_to category.name, category , class: "azul bold"%></li>
        <%end%>
        <% if user_signed_in? %>
          <li><%=link_to "perfil" , perfil_path , class: "azul  bold"%></li>
          <li><%=link_to "Cerrar sesion", destroy_user_session_path, method: :delete , class: "azul bold"%></li>
        <%else%>
          <li><%= link_to "Iniciar sesion", new_user_session_path , class: "azul bold"%></li>
          <li><%= link_to "Crear cuenta", new_user_registration_path , class: "azul bold"%></li>
        <%end%>
      </ul>
      </div>
    </div>
  </nav>
</header>