config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end


    get '/publicar', to: "welcome#publicar"

    get '/perfil', to: "welcome#perfil"
    

    put "/articles/:id/publicar", to: "articles#publicar"
   
    #adiciones que cuando se realize login con omniauth el controlador que se ejecuta 
    #es  omniauth_callbacks
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

    
    
    root 'welcome#index' 

    
    


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_editor!, only: [:perfil]
  before_action :authenticate_admin!, only: [:publicar]
  def index
  	@articles = Article.publicados.ultimos
  end
  
  def publicar
  	@articles = Article.paginate(page: params[:page],per_page:5).ultimos
  end

  def perfil
  	@mis_art_pen = Article.mis_art_pendientes(current_user.id)
    @mis_art_publi = Article.paginate(page: params[:page],per_page:5).mis_art_publicados(current_user.id)
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div id="cont-slider" class="row"> 
 <div class="slider">
    <ul class="slides">
      <% @articles.each do |article| %>
         <%= slider_article article, {id:"slider_img"} %>
      <%end%>
    </ul>
  </div>
</div>


<div class="row center-xs">
  <div class="col-xs-9">
	<h4>Hola 
	<%if user_signed_in? %>
	  <%= current_user.username %>
	<%end%>
	</h4>
  </div>
</div>

app/views/welcome/perfil.html.erb
<div class="row center-xs">
  <div class="col-xs-12 col-sm-12 col-md-8">
    <div class="row">
    <div class="col-xs-12 start-xs">
        <h4>Crear un nuevo articulo</h4>
        <h5><%= link_to 'Nuevo articulo', new_article_path %></h5>  
    </div>
    <% if current_user.permission_level == 3 %> 
    <div class="col-xs-12 start-xs">
        <h4>Acciones administrador</h4>
        <h5><%= link_to 'Publicar articulos', publicar_path %></h5>
        <h5><%= link_to 'Crear categoria', categories_path %></h5> 
    </div>
    <%end%>
    <% if @mis_art_pen != [] %>
        <div class="col-xs-12 start-xs">
           <h4>Articulos sin publicar</h4>    
        </div>
        <div class="col-xs-12">
            <table class="striped">
                <thead>
                    <tr>
                        <th data-field="id">Articulo</th>
                        <th data-field="name">Fecha creado</th>
                        <th data-field="name">Fecha modificado</th>
                    </tr>
                </thead>
                <tbody>
                    <% @mis_art_pen.each do |articulo| %>
                        <td><%= link_to articulo.title, articulo , class: "bold" %></td>
                        <td><%= formato_fecha articulo.created_at %></td>
                        <td><%= formato_fecha articulo.updated_at %>- <%= link_to 'Editar', edit_article_path(articulo) %></td>
                    <%end%>
                </tbody>
            </table>
        </div>
    <%end%>

    <div class="col-xs-12 start-xs">
        <h4>Ultimos articulos publicados</h4>    
    </div>
    <div class="col-xs-12">
        <table class="striped">
            <thead>
                <tr>
                    <th data-field="id">Articulo</th>
                    <th data-field="name">Visitas</th>
                    <th data-field="name">Fecha creado</th>
                    <th data-field="name">Fecha modificado</th>
                </tr>
            </thead>
            <tbody>
                <% @mis_art_publi.each do |articulo| %>
                   <tr>
                    <td><%= link_to articulo.title, articulo, class: "bold" %></td>
                    <td><%= articulo.visitas %></td>
                    <td><%= formato_fecha articulo.created_at %></td>
                    <td><%= formato_fecha articulo.updated_at %>- <%= link_to 'Editar', edit_article_path(articulo) %></td>
                   </tr> 
                <%end%>
            </tbody>
        </table>
    </div>
    <div class="col-xs-12">
        <%= will_paginate @mis_art_publi %>
    </div>
    </div>
  </div>
</div>    

app/views/welcome/publicar.html.erb
<div class="row center-xs">
  <div class=" col-xs-12 col-md-8">
    <h3>Publicar</h3>
    <div class="row">
      <div class="col-xs-12">
          <table class="striped">
              <thead>
                  <tr>
                      <th data-field="id">Articulo</th>
                      <th data-field="name">Visitas</th>
                      <th data-field="name">Fecha creado</th>
                      <th data-field="name">Fecha modificado</th>
                      <th data-field="name">Acciones</th>
                  </tr>
              </thead>
              <tbody>
                  <% @articles.each do |articulo| %>
                     <tr>
                      <td><%= link_to articulo.title, articulo, class: "bold" %></td>
                      <td><%= articulo.visitas %></td>
                      <td><%= formato_fecha articulo.created_at %></td>
                      <td><%= formato_fecha articulo.updated_at %></td>
                      <td>
                        <%= link_to 'Editar', edit_article_path(articulo) , class:"blue darken-4" %>
                        <%= link_to 'Elinimar', articulo, method: :delete, class:"red darken-3",data: { confirm: 'Esta seguro de eliminar?' } %>
                        <% if articulo.may_publicar?%>
                          <%= link_to "Publicar", "/articles/#{articulo.url}/publicar", method: :put , class:"green accent-4" %>
                        <%end%>
                      </td>
                     </tr> 
                  <%end%>
              </tbody>
          </table>
      </div>      
    </div>
    <div class="col-xs-12">
      <%= will_paginate @articles %>
    </div> 
  </div>
</div>