config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end


    get '/publicar', to: "welcome#publicar"

    get '/perfil', to: "welcome#perfil"
    

    put "/articles/:id/publicar", to: "articles#publicar"
   
    #adiciones que cuando se realize login con omniauth el controlador que se ejecuta 
    #es  omniauth_callbacks
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

    
    
    root 'welcome#index' 

    
    


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
    validates :name , presence: true
    has_many :has_categories
    has_many :articles , through: :has_categories

    after_create :update_url
    before_update :asignar_url

     #redefinimos el metodo to_param
    def to_param
        url
    end

    def asignar_url
        self.url = "#{ name.parameterize }"
    end

    def update_url
        update_attributes url: asignar_url
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :authenticate_admin!, except: [:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @articles = @category.articles.paginate(page: params[:page],per_page:15).publicados.ultimos
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by url: params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="col-md-12">
  <%= form_for(@category, html: {  class: "row center-sx center-md" }) do |f| %>
    <div class="col-md-7">
      <div class="row center-xs">

        <div class="input-field col-md-12">
          <%= f.text_field :name ,class:"materialize-textarea"%>
          <label for="category_name">Nombre</label>
        </div>

        <div class="input-field  col-md-12">
          <label for="category_color ">Color</label>
          <%= f.color_field :color %>
        </div>

      </div>

      <div class="col-md-3">
          <button class="btn waves-effect waves-light" type="submit"  name="commit">Crear
          </button>
      </div>
    </div>
      <% end %>
</div>

app/views/categories/edit.html.erb
<div class="row center-xs">
   <div class=" col-md-12 center-align">
   	  <h3>Editar categoria</h3>
   </div>
    <%= render 'form' %>
    
</div>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div class="row center-xs">
    <div class=" col-md-12 center-align">
   	  <h3>Nueva categoria</h3>
   </div>
    <%= render 'form' %>
    
</div>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="row center-xs">
  <div class="col-xs-12 col-sm-12 col-md-9">
    <div class="row">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-xs-12">
            <div class="row start-xs">
              <% @articles.each do |article| %>
                <article class="col-xs-12 col-sm-6 col-md-4">
                    <%= post_article article%> 
                </article>
              <%end%>
            </div>
          </div>
          <div class="col-xs-12">
            <%= will_paginate @articles %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>